### ISSUE TITLE
Generar Plan de Trabajo

### ISSUE THREAD

**Issue by faparraf** [udistrital/autenticacion_documentacion#4]
Se busca generar el plan de trabajo para las dos fases de la modernización de auditoría de la organización. El plan de trabajo debe ser claro y abarcar la la solución completa.

Parte del análisis realizado en la primera fase y busca tener un insumo para el control y planeación de las siguientes etapas, por lo que debe ser lo más apegado a la realidad posible.

**Comment by jdc996** [comment]
Enlace del plan de trabajo para autenticacion unica
https://docs.google.com/spreadsheets/d/1B8DK2TXxMSEMJV27IwMORHn6Rd_VSKYLUWo5aIST7R8/edit?usp=sharing

**Comment by faparraf** [comment]
Plan de Trabajo revisado, se puede cerrar el Issue
