### ISSUE TITLE
Instalación y manual de configuración de entorno de desarrollo local para frameworks antiguos.

### ISSUE THREAD

**Issue by a52290451** [udistrital/autenticacion_documentacion#5]
Realizar la instalación, configuración y su respectiva documentación del entorno de desarrollo local para frameworks antiguos de PHP (SARA) utilizado en este caso por el sistema ÁGORA.

**Criterios de aceptación**

- [x] Instalación y configuración del entorno de desarrollo.
- [x]  Manual de configuración del entorno de desarrollo.

**Comment by criss201x** [comment]
Se realiza configuración del aplicativo Agora en ambiente de desarrollo local con el fin de implementar el flujo de autenticacion única para este tipo de sistemas, adicionalmente se realiza manual de instalación y configuración de 
 aplicaciones SARA con el fin de documentar dicho proceso, en el manual se tomo como ejemplo el aplicativo Agora.

- [Link del manual de configuracion SARA](https://docs.google.com/document/d/1XELFDa5i7mvdsaa7AN9JX5wEPMEX6Vum/edit?usp=sharing&ouid=110288693142592643207&rtpof=true&sd=true)

**Comment by a52290451** [comment]
Se valida manual de configuración presentado.
